### ISSUE TITLE
Enable parameter sweep by ER λ param

### ISSUE THREAD

**Issue by divilian** [WheezePuppet/specstar#11]
Enable parameter sweep by Erdos-Renyi λ parameter, with resulting plots.

**Comment by divilian** [comment]
This will involve:
* write some Julia code in a separate file that calls `specnet()` from sim.jl in a loop with most parameters fixed but one varying through a range
* having this code receive a DataFrame as a return value from `specnet()` (it doesn't do this now, but will shortly) and either concatenate/assemble these into a larger DataFrame or dump them as you go to a .csv file
* write some code (in any language) to make some useful plots. (In this case, the first one to make is a 2-dimensional scatterplot with the ER lambda parameter as x-var and Gini coefficient at simulation's end as the y-var.)

**Comment by divilian** [comment]
@will-nehrboss added the general parameter sweep in 606732d. I'll now add λ functionality, recasting it in terms of the low-level ER parameters.

**Comment by divilian** [comment]
(I lied; I'll let @will-nehrboss do that.)

**Comment by divilian** [comment]
@will-nehrboss: search for "lambda" on this page: https://www.networkpages.nl/erdos-renyi-graph-part-ii/
Basically, I think we want to just switch from having `:N` and `:ER_prob` as parameters to having `:N` and `:λ` as parameters, with `ER_prob` then being determined from `:N` and `:λ`. Correct me if you disagree, @venkatachalapathy.

**Comment by venkatachalapathy** [comment]
You are right @WheezePuppet ! Something similar can also be done for SW networks, @will-nehrboss . If you look at the definition of _small worldness_, you will find that it involves some optimal scaling of path length and clustering coefficient. Only for a particular range of parameters do we get this property satisfied.

**Comment by wkneh** [comment]
@WheezePuppet In my enthusiasm for adding parameters to sweep I must have lost sight of the title of this issue:-). ER lambda will (hopefully) be simple, but if I run into any problems with the small world params I will give you a shout, @venkatachalapathy.
Just curios, why is lambda a better parameter then prob?

**Comment by venkatachalapathy** [comment]
So the lambda parameter is the one that is relevant for an infinite graph. When the no of nodes of the graph are infinite, the binomial degree distribution (defined using N and p) of the graph tends towards a Poisson distribution (defined using lambda). So, it is basically limiting value of the binomial distribution that produces a phase transition.

**Comment by divilian** [comment]
Will fixed this in 4066373.
