### ISSUE TITLE
Katz's discussion of social network structure in Hamilton 

### ISSUE THREAD

**Issue by venkatachalapathy** [WheezePuppet/specstar#17]
In an earlier email thread, I identified chapter 2 as an important place where to extract insights for social network models. Another cursory look took me to chapter 4 where he discusses the entrepreneurial class. 

My hunch is that this suggests community structure _should_ has an important role to play in the class of social network models to be used for simulation. 

So, I should probably give *this* book another read. And probably @IngenuityArts too.

**Comment by divilian** [comment]
Closing this since it no longer appears to be an action item.
