### ISSUE TITLE
Generating inter agent interactions 

### ISSUE THREAD

**Issue by venkatachalapathy** [WheezePuppet/specstar#20]
Building off of #1, we need to develop inter agent interactions once we @WheezePuppet  and @venkatachalapathy resolve the ongoing issues about what we mean by coordination. 

#3 is relevant when we start thinking about this.

**Comment by divilian** [comment]
Agreed. In the current Stejesh model, "inter agent interactions" are limited to:
1. Once per iteration, two random agents are chosen (with probability ~p, these are neighbors in the graph)
2. If these random nodes each have wealth above the threshold, form a "proto" (proto-institution) with those two agents.

...and that's it.

**Comment by divilian** [comment]
pinging this issue, since I'm unsure if it's still relevant. @venkatachalapathy?

**Comment by divilian** [comment]
I think this issue _per se_ is obsolete.
