### ISSUE TITLE
Some issues are importance to ALL our project in general 

### ISSUE THREAD

**Issue by venkatachalapathy** [WheezePuppet/specstar#21]
So, @venkatachalapathy and @WheezePuppet have been tagging issues at our project fork and found it necessary to tag [some of them ](https://github.com/WheezePuppet/specnet/labels/SPECstar) `SPECstar`. These are issues that both all our projects, current and future, have to think about. @IngenuityArts  and @IngenuityArts, take a look at them. We could discuss them during our next conference all.

**Comment by divilian** [comment]
Closing this issue since we have indeed been using this tagging mechanism.
