### ISSUE TITLE
Necessary julia libraries for implementation

### ISSUE THREAD

**Issue by venkatachalapathy** [WheezePuppet/specstar#23]
Looks like Srikanth has not joined this repo yet. When he does, this is a question for him. 

+ What are the libraries in julia that are going to be useful for this project fork?

@srikanthmudigonda and @WheezePuppet , this one's for you.

**Comment by divilian** [comment]
We're using RCall, Gadfly, LightGraphs, and many others. I think this issue _per se_ is obsolete now.
