### ISSUE TITLE
Make pay day and metabolism scape<->net consistent

### ISSUE THREAD

**Issue by divilian** [WheezePuppet/specstar#25]
Make pay day and metabolism scape<->net consistent.

**Comment by divilian** [comment]
@will-nehrboss, feel like taking this one? SPECscape has two parameters: `MtblRate` and `InitSgrLvl`. At least the second of these does not correspond cleanly to anything in SPECnet. First step for this issue is figuring out conceptually how we make the two sides compatible: how fast do agents consume sugar? And how fast do they acquire it?

**Comment by venkatachalapathy** [comment]
I think we figure this out since the issue was last referenced. The current model has both `MtblRate` and `InitSgrLvl` built into it.  This issue no longer needs to be open.
