### ISSUE TITLE
Statistical comparison of Gini coefficients

### ISSUE THREAD

**Issue by venkatachalapathy** [WheezePuppet/specstar#37]
Once we have Gini coefficients from different conditions, we may have to compare them statistically. The issue is to create such tests or compare histograms directly with standard methods.

**Comment by venkatachalapathy** [comment]
@srikanthmudigonda and @WheezePuppet , are there standard tests for this? And in what packages?

**Comment by jeffg828** [comment]
Hmm, ginis are ratios, does that mean two population proportion test?
Asking for a friend.

**Comment by venkatachalapathy** [comment]
https://cran.r-project.org/web/packages/dineq/index.html

https://cran.r-project.org/web/packages/dineq/index.html

both seem to do it (using the proportion test like what you (jeff) suggested) via confidence intervals but since we just removed `RCall` dependencies, we have either create tests from scratch or code it ourselves. But the `ineq` package we used don't seem to have this feature.

and also this one

https://www.rdocumentation.org/packages/DescTools/versions/0.99.19/topics/Gini

**Comment by divilian** [comment]
Surely we're not claiming that standard statistical tests like the ones you learn about in STAT 101 are not available here?? https://github.com/JuliaStats  (See, for instance, https://github.com/JuliaStats/HypothesisTests.jl)  If we actually need to call R from Julia in order to run a freaking t-test, I'll jump off the highest bridge in my field of view with no parachute.

**Comment by venkatachalapathy** [comment]
You don't have to jump of the bridge, Stephen.  t-tests will do for now. I was kind of expecting some _special_ test just for Gini comparisons. t-tests usually assume normally distributed data. I do not know enough about Gini to know if they are asymptotically normally distributed. But OK.... we can make do with what we have ;)

**Comment by jeffg828** [comment]
Hmm, I took a gander at that link... Not so sure about the t test straight
up.  Looks like the distribution for ginis has a funky srandard error.
Worst case, can you export what you need to a file and just run R on the
file?

**Comment by divilian** [comment]
Ah right, normally distributed data, which might well not be true for Ginis. Good point. So, I see that https://github.com/JuliaStats/HypothesisTests.jl also supports Wilcoxon and Mann-Whitney tests -- would these be more appropriate?

(Btw, my "jump off a bridge" comment was not related to t-tests being necessarily the correct thing, but rather the idea that we would have to call out to R for something like this. I would be astonished if whatever the correct test is for this were not implemented natively in Julia.)

**Comment by venkatachalapathy** [comment]
#40 contains links to `R` library `DescTools` 

This should do the job for now.

**Comment by venkatachalapathy** [comment]
I'm closing this as we have enough of this figured out to complete `phase 1` and pushed pushed the two-sample version to `phase 2+`.
