### ISSUE TITLE
Articulate algorithm for detecting stopping condition

### ISSUE THREAD

**Issue by divilian** [WheezePuppet/specstar#41]
Come up with a brilliant and principled way to detect that the simulation has reached equilibrium, or that it has been run "long enough" to sensibly stop. Articulate that plan to the coders so they can implement it.

**Comment by venkatachalapathy** [comment]
__Claim:__ The system does not reach equilibrium 

__Proposed Stopping Rule:__ If the proto with the least wealth can survive a non-trivial starvation shock, the system has sufficiently evolved. 

_Non-trivial starvation shock_ is switching off all income for time order of Variance(wealth)/sqrt(D) where D is the effective white noise intensity for all the agents combined.

__Note:__ I'll make this precise in a doc. I am closing this as the final stopping condition is going to be very similar to this one, even if there are minor changes.
