### ISSUE TITLE
Output proto-related statistics

### ISSUE THREAD

**Issue by divilian** [WheezePuppet/specstar#46]
We need to figure out exactly what this looks like. Candidates for inclusion:

* The number of protos (a time series?)
* The number of agents in each proto (histogram)
* The account balance of each proto (histogram)
* How many protos "survive" based on starvation of a certain duration (see #45)

**Comment by venkatachalapathy** [comment]
No that #45 is done, maybe it is time to look at this one. 

The account balance in a proto is a function of lot other dimensionful parameters of the system. To be at least, it makes more sense to look at starvation shocks and robustness of proto-s to starvation shocks than an absolute account balance. 
+  Time to S1 -> S2 
+  Time to S2 -> S3

are good numbers to plot . 

In the time interval [S1,S2]
+ Growth in the number of protos 
+ Histogram of proto sizes 

And finally, the number of protos that survive a starvation shock (characterized by the duration of starvation)

**Comment by divilian** [comment]
Got it. So, in terms of the five quantities you mention:
1. Number of iterations before S2 begins
2. Number of iterations before S3 begins
3. Growth in number of protos in interval [S1,S2]
4. Histogram of proto sizes in interval [S1,S2]
5. Number of protos that survive a starvation shock

I feel like only 5 is actually related to "robustness of protos to starvation shocks." That's not to say the first four aren't interesting, but just to make sure I understand, those relate to how-fast and in-what-way agents encounter each other and form protos, right?

Also, regarding 5: the way we've been talking so far, the starvation shock will be for a fixed number of iterations (controlled by `:starvation_period`), after which we produce stats again. What about this formulation: the starvation shock is permanent, not temporary, and we run the simulation until apocalypse? Then we could get MTTF stats and so forth for how long agents can survive on a scarred and salted earth.

**Comment by venkatachalapathy** [comment]
You are right that only 5 is related to robustness measure. 

Your further comment regarding 5 is correct and important. In out-of-equilibrium systems (where they use such Markov process models), persistence exponent, the tail survival time is a quantity used to describe such global decay dynamics. If not now, calculating the tail decay exponent from our simulation must be on our to-do for the journal publication.

**Comment by divilian** [comment]
Some of this was addressed in #62. The remainder I am currently working on.

**Comment by divilian** [comment]
The first two of the five items above (number-of-iterations-until-stages-2-and-3) has been added in e38b684.

**Comment by divilian** [comment]
Eleven days ago, I wrote this list:
> 1. Number of iterations before S2 begins
> 2. Number of iterations before S3 begins
> 3. Growth in number of protos in interval [S1,S2]
> 4. Histogram of proto sizes in interval [S1,S2]
> 5. Number of protos that survive a starvation shock

We are now plotting 1, 2, and 5. I'm having trouble visualizing how to visualize 3 and 4, especially in a parameter sweep setting. Both of them refer to "intervals," during which dynamic activity happens during every simulation run. How then to combine these in a meaningful infographic, @venkatachalapathy? (Or should we just skip for now?)

**Comment by divilian** [comment]
@venkatachalapathy says:
>  I am thinking that we can skip this for this round.  It is tough to think of a way to visualize 4). But the growth in the no of protos could be done by simply overlaying the results of all the simulation runs. But then again, what convincing story can we tell with 3) and 4) that we are currently unable to tell with other plots?

I like your idea for 3) (overlaying a number-of-protos-vs-time line plot for each trial run of a particular parameter value) but that only lets us visualize the results of one λ (or whatever parameter) value at a time, right?

I agree with your second point: probably overkill, at least for phase 1.

**Comment by divilian** [comment]
Closing this for now, since I think we're now plotting everything we're going to want to plot for phase 1. Time to focus on analysis of our existing plot space.
