### ISSUE TITLE
Identify meaningful set of wealth/income parameters

### ISSUE THREAD

**Issue by divilian** [WheezePuppet/specstar#49]
Identify the minimal interesting set of wealth/income parameters (probably comprised of some subset of `:init_sg_lvl`, `:metabolic_rate`, `:salary_range`, and `:proto_threshold`, all defined in `setup_params.jl`.)

(Note to @venkatachalapathy: the thing we currently call `:salary_range` will probably change to two things: (1) the fixed salary per iteration per agent, and (2) the std dev of the white noise we add to that. Name these appropriately, even using Greek letters if you wish.)

**Comment by venkatachalapathy** [comment]
I think we sorted this out. I am closing this one. See pinned message inside #analysis channel.
